// <auto-generated />
using APICourse.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APICourse.Migrations
{
    [DbContext(typeof(CourseContext))]
    [Migration("20230423232257_adiciona_coluna_status")]
    partial class adiciona_coluna_status
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("APICourse.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK_Id_tbCourse");

                    b.ToTable("tbCourse");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "back-end",
                            Name = "Java",
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 2,
                            Category = "back-end",
                            Name = "C sharp",
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 3,
                            Category = "front-end",
                            Name = "Angular",
                            Status = "Ativo"
                        },
                        new
                        {
                            Id = 4,
                            Category = "front-end",
                            Name = "React JS",
                            Status = "Ativo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
